### PR TITLE
fix: `shimDisconnect: false` behavior

### LINKED ISSUE #3828: shimDisconnect is ignored
### Describe the bug

Ref:
https://github.com/wevm/wagmi/issues/3603

I've put breakpoints inside injected.js file debugger. You can see that `injected` is called two times, and for the second time it's called with shimDisconnect undefined => true:
image

And after that the code that should not be run, is actually run: 
image

I've extensively described the process here: https://github.com/wevm/wagmi/pull/3608

### Link to Minimal Reproducible Example

_No response_

### Steps To Reproduce

_No response_

### Wagmi Version

@wagmi/core@2.6.17

### Viem Version

2.9.19

### TypeScript Version

_No response_

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by tmm**
### Description

fixes #3828
closes #3829

### CODE REVIEW

File: packages/core/src/connectors/injected.ts [hunk 1]
```diff
@@ -223,13 +223,13 @@ export function injected(parameters: InjectedParameters = {}) {
...
+        if (shimDisconnect)
           await config.storage?.removeItem(`${this.id}.disconnected`)
-          // Add connected shim if no target exists
-          if (!parameters.target)
-            await config.storage?.setItem('injected.connected', true)
-        }
+
+        // Add connected shim if no target exists
+        if (!parameters.target)
+          await config.storage?.setItem('injected.connected', true)
```
Comment (tmm) [inline packages/core/src/connectors/injected.ts:232]: flag needs to be set even if `shimDisconnect: false`

https://github.com/wevm/wagmi/blob/f612323f2dd9a80cc5be43f0bc9fd08c31aeb65c/packages/core/src/connectors/injected.ts#L316
